import { NextRequest, NextResponse } from 'next/server';

// Mapowanie pierwszych 3 cyfr kodu routingowego NRB na nazwy banków
// Źródło: KIR / Związek Banków Polskich — lista kodów rozliczeniowych
const BANK_CODES: Record<string, string> = {
  // NBP
  '101': 'NBP',
  '102': 'NBP',
  // PKO Bank Polski
  '103': 'Bank BPH',
  '104': 'PKO Bank Polski',
  '105': 'ING Bank Śląski',
  '106': 'Bank BPH',
  '107': 'PKO Bank Polski',
  '108': 'PKO Bank Polski',
  '109': 'Santander Bank Polska',
  '110': 'PKO Bank Polski',
  '111': 'PKO Bank Polski',
  '112': 'PKO Bank Polski',
  '113': 'BNP Paribas Bank Polska',
  '114': 'mBank',
  '115': 'mBank',
  '116': 'Santander Bank Polska',
  '117': 'PKO Bank Polski',
  '118': 'PKO Bank Polski',
  '119': 'PKO Bank Polski',
  '120': 'PKO Bank Polski',
  '121': 'PKO Bank Polski',
  '122': 'Bank Handlowy (Citi)',
  '123': 'PKO Bank Polski',
  '124': 'PKO Bank Polski',
  '125': 'PKO Bank Polski',
  '126': 'PKO Bank Polski',
  '127': 'PKO Bank Polski',
  '128': 'HSBC',
  '129': 'PKO Bank Polski',
  '130': 'BNP Paribas Bank Polska',
  '131': 'Bank Pocztowy',
  '132': 'Bank Pocztowy',
  '133': 'PKO Bank Polski',
  '134': 'Bank Spółdzielczy',
  '135': 'Bank Spółdzielczy',
  '136': 'Bank Spółdzielczy',
  '137': 'Bank Spółdzielczy',
  '138': 'Bank Spółdzielczy',
  '139': 'Bank Spółdzielczy',
  '140': 'Bank Spółdzielczy',
  '141': 'Bank Spółdzielczy',
  '142': 'Bank Spółdzielczy',
  '143': 'BNP Paribas Bank Polska',
  '144': 'Bank Spółdzielczy',
  '145': 'Bank Spółdzielczy',
  '146': 'Bank Spółdzielczy',
  '147': 'Bank Spółdzielczy',
  '148': 'Bank Spółdzielczy',
  '149': 'Bank Spółdzielczy',
  '150': 'Bank Spółdzielczy',
  '151': 'Bank Spółdzielczy',
  '152': 'Bank Spółdzielczy',
  '153': 'Bank Spółdzielczy',
  '154': 'BOŚ Bank',
  '155': 'Bank Spółdzielczy',
  '156': 'Bank Spółdzielczy',
  '157': 'Bank Spółdzielczy',
  '158': 'Bank Spółdzielczy',
  '159': 'Bank Spółdzielczy',
  '160': 'Getin Noble Bank',
  '161': 'Getin Noble Bank',
  '162': 'Bank Spółdzielczy',
  '163': 'Bank Spółdzielczy',
  '164': 'Bank Spółdzielczy',
  '165': 'Bank Spółdzielczy',
  '166': 'Bank Spółdzielczy',
  '167': 'Bank Spółdzielczy',
  '168': 'Plus Bank',
  '169': 'Bank Spółdzielczy',
  '170': 'Bank Spółdzielczy',
  '171': 'Bank Spółdzielczy',
  '172': 'Bank Spółdzielczy',
  '173': 'Bank Spółdzielczy',
  '174': 'Bank Spółdzielczy',
  '175': 'Raiffeisen Bank Polska',
  '176': 'Bank Spółdzielczy',
  '177': 'Bank Spółdzielczy',
  '178': 'Bank Spółdzielczy',
  '179': 'Bank Spółdzielczy',
  '180': 'Bank Spółdzielczy',
  '181': 'Bank Spółdzielczy',
  '182': 'Bank Spółdzielczy',
  '183': 'Bank Spółdzielczy',
  '184': 'Alior Bank',
  '185': 'Bank Spółdzielczy',
  '186': 'Bank Spółdzielczy',
  '187': 'Nest Bank',
  '188': 'Bank Spółdzielczy',
  '189': 'Bank Pekao SA',
  '190': 'Bank Spółdzielczy',
  '191': 'Bank Spółdzielczy',
  '192': 'Bank Spółdzielczy',
  '193': 'Credit Agricole Bank Polska',
  '194': 'Deutsche Bank Polska',
  '195': 'Bank Millennium',
  '196': 'Bank Spółdzielczy',
  '197': 'Bank Spółdzielczy',
  '198': 'Bank Spółdzielczy',
  '199': 'Bank Spółdzielczy',
  '200': 'Bank Spółdzielczy',
  '201': 'Bank Spółdzielczy',
  '202': 'Bank Spółdzielczy',
  '203': 'Bank Pekao SA',
  '204': 'Bank Spółdzielczy',
  '205': 'Bank Pekao SA',
  '206': 'Bank Spółdzielczy',
  '207': 'Bank Spółdzielczy',
  '208': 'Bank Spółdzielczy',
  '209': 'Bank Spółdzielczy',
  '210': 'Bank Spółdzielczy',
  '211': 'Bank Spółdzielczy',
  '212': 'PKO Bank Polski',
  '213': 'Santander Bank Polska',
  '214': 'mBank',
  '215': 'mBank',
  '216': 'mBank',
  '217': 'Bank Spółdzielczy',
  '218': 'ING Bank Śląski',
  '219': 'ING Bank Śląski',
  '220': 'Bank Spółdzielczy',
  '221': 'Bank Spółdzielczy',
  '222': 'Bank Spółdzielczy',
  '223': 'Bank Spółdzielczy',
  '224': 'PKO Bank Polski',
  '225': 'Bank Spółdzielczy',
  '226': 'Bank Spółdzielczy',
  '227': 'Bank Spółdzielczy',
  '228': 'Bank Spółdzielczy',
  '229': 'Santander Bank Polska',
  '230': 'Bank Spółdzielczy',
  '231': 'Bank Spółdzielczy',
  '232': 'Bank Spółdzielczy',
  '233': 'Bank Spółdzielczy',
  '234': 'Bank Spółdzielczy',
  '235': 'Bank Spółdzielczy',
  '236': 'Bank Spółdzielczy',
  '237': 'Bank Spółdzielczy',
  '238': 'Bank Spółdzielczy',
  '239': 'Bank Spółdzielczy',
  '240': 'Bank Spółdzielczy',
  '241': 'Bank Spółdzielczy',
  '242': 'Bank Spółdzielczy',
  '243': 'BNP Paribas Bank Polska',
  '244': 'Bank Spółdzielczy',
  '245': 'Bank Spółdzielczy',
  '246': 'Bank Spółdzielczy',
  '247': 'Eurobank',
  '248': 'Santander Consumer Bank',
  '249': 'Alior Bank',
  '250': 'Bank Spółdzielczy',
  '251': 'Bank Spółdzielczy',
  '252': 'Bank Spółdzielczy',
  '253': 'Bank Spółdzielczy',
  '254': 'Bank Spółdzielczy',
  '255': 'Bank Spółdzielczy',
  '256': 'Bank Spółdzielczy',
  '257': 'Bank Spółdzielczy',
  '258': 'Bank Spółdzielczy',
  '259': 'Bank Spółdzielczy',
  '260': 'Bank Spółdzielczy',
  '261': 'Bank Spółdzielczy',
  '262': 'Bank Spółdzielczy',
  '263': 'Bank Spółdzielczy',
  '264': 'Bank Spółdzielczy',
  '265': 'PKO Bank Polski',
  '266': 'Bank Spółdzielczy',
  '267': 'Bank Spółdzielczy',
  '268': 'Bank Spółdzielczy',
  '269': 'Bank Spółdzielczy',
  '270': 'Bank Spółdzielczy',
  '271': 'Bank Spółdzielczy',
  '272': 'Bank Pekao SA',
  '273': 'Bank Spółdzielczy',
  '274': 'Bank Pekao SA',
  '275': 'Bank Spółdzielczy',
  '276': 'Bank Spółdzielczy',
  '277': 'Bank Spółdzielczy',
  '278': 'Bank Spółdzielczy',
  '279': 'Bank Spółdzielczy',
  '280': 'HSBC',
  '281': 'Bank Spółdzielczy',
  '282': 'Bank Spółdzielczy',
  '283': 'Bank Spółdzielczy',
  '284': 'Bank Spółdzielczy',
  '285': 'Bank Spółdzielczy',
  '286': 'Bank Spółdzielczy',
  '287': 'Bank Spółdzielczy',
  '288': 'Bank Spółdzielczy',
  '289': 'Bank Spółdzielczy',
  '290': 'Bank Spółdzielczy',
  '291': 'Bank Spółdzielczy',
  '292': 'Bank Spółdzielczy',
  '293': 'Bank Spółdzielczy',
  '294': 'Bank Spółdzielczy',
  '295': 'Bank Spółdzielczy',
  '296': 'Bank Spółdzielczy',
  '297': 'Bank Spółdzielczy',
  '298': 'Bank Spółdzielczy',
  '299': 'Bank Spółdzielczy',
  // SKOK-i
  '611': 'SKOK',
  '612': 'SKOK',
  '613': 'SKOK',
  '614': 'SKOK',
  '615': 'SKOK',
  '619': 'SKOK',
  '621': 'SKOK',
  '625': 'SKOK',
  '641': 'SKOK',
  '648': 'SKOK',
  '651': 'SKOK',
  '671': 'SKOK',
  '872': 'SKOK',
};

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const raw = searchParams.get('iban') ?? '';
  const iban = raw.replace(/\s+/g, '').toUpperCase();

  if (!iban || iban.length < 26) {
    return NextResponse.json({ bank: null });
  }

  // NRB = 26 cyfr (PL-IBAN bez przedrostka PL, lub bezpośrednio NRB)
  const nrb26 = iban.startsWith('PL') ? iban.slice(2) : iban;

  // Pierwsze 3 cyfry kodu routing (pozycje 2–4 NRB, bo 0–1 to cyfry kontrolne)
  const code3 = nrb26.slice(2, 5);
  const bankName = BANK_CODES[code3] ?? `Nieznany bank (${code3})`;

  return NextResponse.json({ bank: bankName });
}
